version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_3101Project
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SSL_JDBC_Test
  version: "1.0"
  gitServerName: SIQAPsur
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
- name: JMS2waySSL
  version: "1.0"
  gitServerName: SIQAPsur
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
services:
- serviceName: project.siqa_3101.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_3101Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: project.siqa_3101.integrations:SSL_JDBC_test
  packages:
  - name: SIQA_3101Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: SSL_JDBC_Test.services:insert_ssl
  packages:
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_3101.integrations:Sum
  packages:
  - name: SIQA_3101Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: project.siqa_3101.integrations:Twoway_pub
  packages:
  - name: SIQA_3101Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: publisher:publisher
  packages:
  - name: JMS2waySSL
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: project.siqa_3101.integrations:deepclonetest
  packages:
  - name: SIQA_3101Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
configurationVariables:
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.expireTime: "60000"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  jdbc.jdbcTestPool.spyenabled: "false"
  jdbc.jdbcTestPool.snoopenabled: "false"
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  jdbc.jdbcTestPool.useSSL: "false"
